export enum ErrorCodeEnum {
  /* ========= USERS ========= */
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  /* ========= ACCOUNTS ========= */
  ACCOUNT_EXISTS = 'ACCOUNT_EXISTS',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',

  /* ========= AVITO ========= */
  AVITO_GET_TOKEN_ERROR = 'AVITO_GET_TOKEN_ERROR',

  /* ========= GENERAL ========= */
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  TOO_MANY_ATTEMPTS = 'TOO_MANY_ATTEMPTS',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  NOT_ALLOWED = 'NOT_ALLOWED',
  RESOURCE_NOT_FOUND = 'RECOURCE_NOT_FOUND',
}
