export enum ErrorCodeEnum {
  /* ========= USERS ========= */
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  /* ========= ACCOUNTS ========= */
  ACCOUNT_EXISTS = 'ACCOUNT_EXISTS',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',

  /* ========= CHATS ========= */
  CHAT_NOT_FOUND = 'CHAT_NOT_FOUND',

  /* ========= ITEMS ========= */
  ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',

  /* ========= MESSAGES ========= */
  MESSAGE_NOT_SEND = 'MESSAGE_NOT_SEND',

  /* ========= AVITO ========= */
  AVITO_GET_TOKEN_ERROR = 'AVITO_GET_TOKEN_ERROR',

  /* ========= WEBHOOKS ========= */
  WEBHOOK_MESSAGE_WAS_RECEIVED = 'WEBHOOK_MESSAGE_WAS_RECEIVED',
  WEBHOOK_INVALID_MESSAGE_PAYLOAD = 'WEBHOOK_INVALID_MESSAGE_PAYLOAD',
  WEBHOOK_INVALID_PROCESSED = 'WEBHOOK_INVALID_PROCESSED',

  /* ========= GENERAL ========= */
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  TOO_MANY_ATTEMPTS = 'TOO_MANY_ATTEMPTS',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  NOT_ALLOWED = 'NOT_ALLOWED',
  RESOURCE_NOT_FOUND = 'RECOURCE_NOT_FOUND',
}
